apiVersion: v1
kind: Service
metadata:
  name: scaling-agent
spec:
  selector:
    app: scaling-agent
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP  # Change to LoadBalancer if needed
